### ISSUE TITLE
'KDLKinematics' object has no attribute 'gravity'

### ISSUE THREAD

**Issue by QAbot-zh** [ochoa92/Master-Thesis#1]
hello，Have you modify the pykdl_utils library? I install the pykdl_utils from [hrl-kdl](https://github.com/gt-ros-pkg/hrl-kdl.git), But when I run the script, I got some error as below:
```
# the script 
rosrun thesis_demo joint_pos_control.py
```
And the error Information : 
```
TORQUE CONTROLLER MODE!
Traceback (most recent call last):

Press <ENTER> to interrupt the main loop!
  File "/home/zxy/kinova-polish-ws/src/jaco-polish/thesis_demo/nodes/joint_pos_control.py", line 521, in <module>
    main()
  File "/home/zxy/kinova-polish-ws/src/jaco-polish/thesis_demo/nodes/joint_pos_control.py", line 373, in main
    g = np.transpose(np.matrix(kin.gravity(q)))  # gravity matrix
AttributeError: 'KDLKinematics' object has no attribute 'gravity'
```
If you use another source to install pykdl_utils OR you modify the pykdl_utils library, Could you share some experience to me ?

**Comment by QAbot-zh** [comment]
Oooohhhh, I didn't notice that the  ../thesis_demo/orocos/pykdl_utils folder, Sorry.
